### ISSUE TITLE
conn.connected() actually work?

### ISSUE THREAD

**Issue by leo-combes** [Trakkasure/mikronode#41]
Seems the conn.connected () return nothing.
Do conn.connected () still work?

```
var device = new MikroNode('10.0.140.14');
device.connect('user', 'password', {'port': '8291'}).then(function(conn) {
      console.log(conn.connected());  // return nothing
   },function(err) {
      d.resolve("Error connecting API:",err);
   });
```

**Comment by Trakkasure** [comment]
That method doesn't exist in the new library.
The resolution of the promise confirms that you're connected.
If logging in fails, then the promise rejects.

Also, port is no longer an option when connecting. Provide port as the second option when creating the instance of MikroNode. The third option is a connection timeout as a number of seconds.

The idea in doing it that was that each device is it's own configuration, and each device *could* be connected to multiple times for whatever reason.

I will put a read-only connected property in order to help for when you're not inside the promise's then handler.

**Comment by leo-combes** [comment]
> I will put a read-only connected property in order to help for when you're not inside the promise's then handler

It's exactly what I need.
Thanks also for clarifying the timeout parameter, I was testing it yesterday and it did not work for me. Now I'll see if I was in the right place.

**Comment by leo-combes** [comment]
I am confused about setting parameters in connection. I try in several ways, but no luck setting port and timeout.

simplest connection:
```
device = new MikroNode(ip);
device.connect('user', 'password').then(function(conn)
```

Trying set port and 5 seconds timeout, none work:
```
device.connect('user', 'password', 8728, 5).then(function(conn)
device.connect('user', 'password', {'port': 8728, 'timeout': 5).then(function(conn)
device.setTimeout(3);
```

Which is the right way of do this? Also, is it possible to activate some kind of debug mode?

**Comment by Trakkasure** [comment]
The port and timeout go in the construction of the device, not in the connect method.

**Comment by Trakkasure** [comment]
An example:
```javascript
var device = new MikroNode('10.0.140.14', 8728, 5);
```

**Comment by leo-combes** [comment]
Thanks for reply!

I'm testing it the way you suggest it, it connects correctly, but it never disconnects due to inactivity.
That is, all I do is connect and wait without sending any commands, it never disconnects.
It should be disconnected after 5 seconds, right?

**Comment by Trakkasure** [comment]
It's not inactivity timeout, it's "socket" timeout. It's a low-level TCP thing that is useful for when it is possible that the device becomes disconnected due to wireless interference, or other network issues (ex:bad route saved).

If you want inactivity timeout, I would suggest taking advantage of the capabilities of RxJS.
The API takes full advantage of RxJS to do some amazing things.
These are the Observable streams on the Channel object:

* **chan.stream**: All data, unfiltered (Data, trap, done, and fatal events are accessible from this stream)
* **chan.data**: Only packets (sentences) from the device with data are in this stream.
* **chan.trap**: Trap events from the device happen on this stream.
*  **chan.done**: When a command is complete, the MT API sends a "done" event. This allows you to grab ALL data at one time from the executed API command.

Example of timeout:
```javascript
device.connect(...).then((conn)=>{
    const chan=conn.openChannel();
    // Write listen to watch DHCP lease updates. This API cmd was best guess, it might be a little different
    chan.write('/ip/dhcp-server/lease/listen');
    // In 60 seconds, just force-close the channel, canceling the listen command.
    setTimeout(function(){chan.close(true);},60*1000)
    // Normally, we would subscribe.. but for our timeout case, we can, well, have a timeout require that data keeps coming, or throw an error.
    // chan.data.subscribe
    chan.data
        .timeout(10*1000,"We've waited to long! Something should have asked for an address by now!")
        .subscribe(
            (d)=>console.log("We got some data...",d),
            // The error could be the timeout, or it could be a trap from the API. You'll need to check based on the message received in "e"
            (e)=>console.log("An error was thrown:",e),
            ()=>console.log("Stream complete.")
        );
    });
});
```
* RxJS timeout documentation: http://reactivex.io/documentation/operators/timeout.html
* FYI: An error emitted on the stream will cancel the subscription for that iteration. IE: the subscribe function will not get any more data from the channel. You'll have to subscribe again, or use the RxJS catch, or retry operators.

**Comment by leo-combes** [comment]
Thanks for the detailed explanation, I will try it.
Thanks for your time and for sharing this piece of software!
